### PR TITLE
Fix vuln of moment.js < 2.19.3

### PR DESCRIPTION
**Pull request by datengraben**
This replaces moment.js with min version of 2.19.4 from the github repo  https://raw.githubusercontent.com/moment/moment/2.19.4/min/moment.min.js

I saw it when I screened my page with pagespeed.web.dev.
https://security.snyk.io/vuln/npm:moment:20170905

I haven't tested the change until now.
Maybe we can even go with a more recent version of momentjs.

Thanks for creating and maintaining the plugin :)

### CODE REVIEW

**Comment by hansmorb** [comment]
Thank you for your PR, we will look into it.

**Comment by datengraben** [comment]
I hope it is okay if proceed. I checked the changelog of momentjs, doesn't seem the api changed much from 2.18.1 to 2.19.4. Mostly bugfixes.

https://github.com/moment/moment/blob/2.19.4/CHANGELOG.md

Also I increased the version suffix in the wp plugin defintion, forgot about it.

**Comment by chriwen** [comment]
Thank you @datengraben for your PR. As moment seems to be deprecated, should we change to another library? 

https://nilmanduil.medium.com/in-fact-moment-js-is-deprecated-the-development-team-recommends-to-use-date-fns-instead-ad85de96e534

@hansmorb

**Comment by datengraben** [comment]
Sounds good, as the vulnerability isn't directly affecting the client side code, there is no hurry (I realized it now).

We use `date`, `format`, `isAfter` and `add` api from moment js.
On the one hand date-fns is an overkill for the feature set that commonsbooking requires, on the other hand it looks like you can use a minimal version of it and they claim the minimal version uses only 300 bytes. Overall size seems 16kb, when compressed.
https://blog.date-fns.org/post/we-cut-date-fns-v2-minimal-build-size-down-to-300-bytes-and-now-its-the-smallest-date-library-18f2nvh2z0yal/

Day.js seems also like good alternative to me, their api matches also commonsbooking requirements and the size is 2kb (compared to 50kb our momentjs file has atm)

But I you guys have more experience with the requirements of commonsbooking and its users :)

**Comment by hansmorb** [comment]
We could also consider using npm to manage our dependencies and pack them using webpack, this way we don't have to manually update them each time.

**Review by hansmorb — APPROVED** [review]

**Review by chriwen — APPROVED** [review]

**Comment by chriwen** [comment]
@hansmorb Sollen wir das dann erstmal in den master fürs nächste Release integrieren?

**Pull request merged**
